function drawFixationCross(cfg, color)
    % Define the parameters of the fixation cross in `cfg` and `expParameters`

    Screen('DrawLines', ...
        cfg.win, ...
        cfg.allCoords, ...
        cfg.lineWidthPix, ...
        color, ...
        [cfg.center(1) cfg.center(2)], 1);

end
