name: Check Markdown

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1

    - uses: actions/setup-node@v2
      with:
        node-version: '10'

    - name: Install dependencies and check markdown
      run: |
        npm install `cat npm-requirements.txt`
        npx remark . --frail  


