name: Check Markdown links

# checking for any dead links in markdown files

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*']

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
