name: tests and coverage

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: ['*']

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: MOxUnit Action
      uses: joergbrech/moxunit-action@v1.3.0
      with:
        tests: tests
        src: src
        with_coverage: true
        cover_xml_file: coverage.xml

    - name: Code coverage
      uses: codecov/codecov-action@v3
      with:
       token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
       file:  coverage.xml # optional
       flags: unittests # optional
       name: codecov-umbrella # optional
       fail_ci_if_error: false # optional (default = false)
